on: [push]
name: build
jobs:
  tests:
    name: MolecularAssembler Test
    runs-on: ubuntu-latest # or macOS-latest, or windows-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix-build release.nix
